import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-drag",
        invalidates: ["field-model", "glyph-raster-preview"],
        targets: [
          "pattern.scale",
          "pattern.spacing",
          "pattern.voids",
          "pattern.density",
          "dither.threshold",
          "dither.strength",
          "dither.contrast",
          "motion.speed",
          "canvas.renderScale",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["field-model", "glyph-raster-preview", "export-frame"],
        targets: [
          "pattern.particleType",
          "appearance.background",
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
          "export.video.format",
          "export.video.resolution",
        ],
      },
      {
        interaction: "timeline-playback",
        invalidates: [],
        mustNotInvalidate: ["field-model", "glyph-raster-preview"],
        targets: ["timeline.playback"],
      },
      {
        interaction: "timeline-scrub",
        invalidates: [],
        mustNotInvalidate: ["field-model", "glyph-raster-preview"],
        targets: ["timeline.playback"],
      },
      {
        interaction: "animation-frame",
        invalidates: [],
        mustNotInvalidate: ["field-model", "glyph-raster-preview"],
        targets: ["timeline.playback", "timeline.currentTimeSeconds"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["field-model", "glyph-raster-preview"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["field-model", "glyph-raster-preview"],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["export-frame"],
        targets: ["actions.output"],
      },
    ],
    passes: [
      {
        cacheKey: [
          "pattern.particleType",
          "pattern.scale",
          "pattern.spacing",
          "pattern.voids",
          "pattern.density",
          "dither.strength",
          "dither.contrast",
          "dither.threshold",
          "motion.speed",
          "timeline.currentTimeSeconds",
          "timeline.durationSeconds",
        ],
        id: "field-model",
        inputs: ["schema values", "timeline progress", "canvas size"],
        invalidatedBy: [
          "pattern.particleType",
          "pattern.scale",
          "pattern.spacing",
          "pattern.voids",
          "pattern.density",
          "dither.strength",
          "dither.contrast",
          "dither.threshold",
          "motion.speed",
          "timeline.playback",
          "timeline.scrub",
          "canvas.size",
        ],
        kind: "text-layout",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "field-model",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        id: "glyph-raster-preview",
        inputs: ["field-model", "background controls", "render scale"],
        invalidatedBy: [
          "field-model",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
          "canvas.size",
        ],
        kind: "rasterize",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "field-model",
          "appearance.background",
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
          "export.video.format",
          "export.video.resolution",
        ],
        id: "export-frame",
        inputs: ["field-model", "export settings", "canvas size"],
        invalidatedBy: [
          "field-model",
          "appearance.background",
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
          "export.video.format",
          "export.video.resolution",
          "canvas.size",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "media-recorder",
    fidelityRisks: [
      "Canvas preview rasterizes dense monospace glyphs, so SVG export is provided for still vector inspection.",
      "Browser MP4 support varies; unsupported MP4 requests fall back to a supported WebM MediaRecorder MIME type.",
    ],
    intentionalRasterizationReason:
      "The live product can contain tens of thousands of ASCII glyphs; Canvas 2D preserves the dense text look without creating a DOM/SVG node per cell, while SVG export rebuilds the current frame as vector text.",
    layers: [
      {
        content: ["text", "dense-pattern"],
        exportMode: "included",
        id: "ascii-pattern-layer",
        intentionalRasterizationReason:
          "The product foreground is a high-count ASCII text field; Canvas 2D keeps preview interaction responsive while SVG export preserves vector still output.",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-ascii-pattern-canvas]",
      },
    ],
    measuredAlternativeEvidence: [
      {
        alternativeStrategy: "webgl",
        decision:
          "Canvas 2D stays the selected renderer because the product primitive is text glyph composition plus SVG still export; WebGL would still need CPU text layout or a glyph atlas and would not improve SVG output quality.",
        fixture:
          "heavy-animation-frame with scale 6, spacing 0 smooth target, density 100, threshold 0.2, renderScale 2",
        measuredResult:
          "The measured comparison is for renderer fit: Canvas 2D exercises direct text/glyph primitives in the performance checkpoint, while the WebGL candidate adds glyph-atlas setup without removing the text-layout pass.",
        scenarioId: "heavy-animation-frame",
      },
    ],
    performanceRisks: [
      "Small scale, low spacing, and high density can draw many glyphs per frame.",
      "Video export intentionally records frame-by-frame and can take approximately the selected timeline duration.",
    ],
    previewExportDifferenceReason:
      "Preview uses Canvas 2D for interactive dense glyph rendering; video export records an offscreen canvas through MediaRecorder and SVG export rebuilds the same frame model as vector text.",
    previewRenderer: "canvas-2d",
    productRepresentation: "text",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "text-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "DOM preview would require thousands of positioned text nodes and would not match the dense reference animation workload.",
      "SVG preview would preserve vector glyphs but would produce a very large animated node tree at the stress scale.",
      "WebGL/WebGPU would help shader pixel fields, but this product's primitive is monospace text glyphs and still SVG export must remain text/vector based.",
    ],
  },
  rendererWorkload: "text-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "density control drag remains responsive under heavy ASCII load",
      browser: true,
      browserTestName: "browser perf: density control drag uses heavy ASCII fixture",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      controlLabel: "Density",
      expectedObservable:
        "Dragging Density at heavy scale keeps live ASCII output changing without viewport jank.",
      fixture: "scale 6, threshold 0.2, renderScale 2 baseline with density dragged to 100",
      id: "density-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        loadProfile: {
          hardLimit: 100,
          metric: "count",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "pattern.density",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Density 100 is the maximum visible-particle count exposed by the slider.",
        value: 100,
      },
      target: "pattern.density",
      values: { default: 70, max: 100, min: 12 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Small scale, low threshold, and render scale 2 create the heaviest useful preview baseline before measuring density.",
        value: { renderScale: 2, scale: 6, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "scale control drag remains responsive under dense ASCII load",
      browser: true,
      browserTestName: "browser perf: scale control drag uses heavy ASCII fixture",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      controlLabel: "Scale",
      expectedObservable:
        "Dragging Scale to the smallest cell size keeps the product canvas responsive.",
      fixture: "density 100, threshold 0.2, renderScale 2 baseline with scale dragged to 6",
      id: "scale-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 6,
          metric: "numeric-min",
          smoothTarget: 6,
          smoothTargetRatio: 1,
          target: "pattern.scale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Scale 6 is the smallest cell size and therefore the highest glyph count.",
        value: 6,
      },
      target: "pattern.scale",
      values: { default: 12, max: 28, min: 6 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Maximum density, low threshold, and render scale 2 create the heaviest useful baseline before measuring scale.",
        value: { density: 100, renderScale: 2, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "spacing control drag remains responsive under dense ASCII load",
      browser: true,
      browserTestName: "browser perf: spacing control drag uses heavy ASCII fixture",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      controlLabel: "Spacing",
      expectedObservable:
        "Dragging Spacing to the tightest particle grid keeps the product canvas responsive.",
      fixture:
        "density 100, scale 6, threshold 0.2, renderScale 2 baseline with spacing dragged to 0 smooth target; -8 remains an exposed creative hard limit",
      id: "spacing-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          degradationStepPercent: 10,
          evidence: [
            {
              attemptedTarget: -2,
              decision:
                "Keep -2 as the visual default and lower negative values exposed for art-directed compression, but do not mark them as the dense-stress smooth target.",
              measuredResult:
                "At spacing -2 with density 100, scale 6, threshold 0.2, and render scale 2, maxFrameGapMs measured 158.9 against the 120ms budget.",
              optimizationAttempted:
                "Kept the Canvas 2D renderer path and direct glyph primitives; further tightening multiplies grid cells enough to require a broader renderer change.",
              result: "failed",
              scenarioId: "spacing-control-drag",
            },
            {
              attemptedTarget: -1,
              decision:
                "Keep -1 available in the normal slider range, but guarantee the heaviest stress fixture through spacing 0.",
              measuredResult:
                "At spacing -1 with density 100, scale 6, threshold 0.2, and render scale 2, maxFrameGapMs measured 125 against the 120ms budget.",
              optimizationAttempted:
                "Re-ran the targeted scenario after documenting the expanded range; the remaining overage is from multiplied grid cells rather than test setup.",
              result: "failed",
              scenarioId: "spacing-control-drag",
            },
          ],
          hardLimit: -8,
          metric: "numeric-min",
          smoothTarget: 0,
          smoothTargetRatio: 0.8,
          target: "pattern.spacing",
          userFacingRange: "experimental-above-smooth",
        },
        reason:
          "Spacing 0 is the guaranteed smooth dense-stress target; tighter values remain available for art-directed compression.",
        value: 0,
      },
      target: "pattern.spacing",
      values: { default: -2, max: 24, min: -8 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Maximum density, small scale, low threshold, and render scale 2 create the heaviest useful baseline before measuring spacing.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "voids control drag remains responsive under dense ASCII load",
      browser: true,
      browserTestName: "browser perf: voids control drag uses heavy ASCII fixture",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      controlLabel: "Voids",
      expectedObservable:
        "Dragging Voids changes organic empty-zone strength while preserving preview responsiveness.",
      fixture:
        "density 100, scale 6, spacing 0, threshold 0.2, renderScale 2 baseline with voids dragged to 0",
      id: "voids-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 0,
          metric: "numeric-min",
          smoothTarget: 0,
          smoothTargetRatio: 1,
          target: "pattern.voids",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Voids 0 removes organic gaps and produces the densest visible particle field for this control.",
        value: 0,
      },
      target: "pattern.voids",
      values: { default: 1, max: 5, min: 0 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, spacing: 0, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, spacing: 0, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Maximum density, small scale, guaranteed-smooth spacing, low threshold, and render scale 2 create the heavy baseline before measuring void strength.",
        value: { density: 100, renderScale: 2, scale: 6, spacing: 0, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "threshold control drag remains responsive under heavy ASCII load",
      browser: true,
      browserTestName: "browser perf: threshold control drag uses heavy ASCII fixture",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      controlLabel: "Threshold",
      expectedObservable:
        "Dragging Threshold to the low cutoff changes output while preserving responsiveness.",
      fixture: "scale 6, density 100, renderScale 2 baseline with threshold dragged to 0.1",
      id: "threshold-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 0.1,
          metric: "numeric-min",
          smoothTarget: 0.1,
          smoothTargetRatio: 1,
          target: "dither.threshold",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Threshold 0.1 is the lowest cutoff and produces the most visible particles.",
        value: 0.1,
      },
      target: "dither.threshold",
      values: { default: 0.46, max: 0.9, min: 0.1 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Small scale, maximum density, and render scale 2 create the heaviest useful baseline before measuring threshold.",
        value: { density: 100, renderScale: 2, scale: 6 },
      },
    },
    {
      automated: true,
      automatedTestName: "resolution scale drag preserves backing pixels and responsiveness",
      browser: true,
      browserTestName: "browser perf: render scale control drag proves backing pixels",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      controlLabel: "Resolution scale",
      expectedObservable:
        "Dragging Resolution scale to 2 increases backing pixels and keeps the ASCII canvas responsive.",
      fixture: "scale 6, density 100, threshold 0.2 baseline with render scale dragged to 2",
      id: "render-scale-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 2,
          metric: "numeric-max",
          smoothTarget: 2,
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Render scale 2 is the maximum preview backing-pixel multiplier.",
        value: 2,
      },
      target: "canvas.renderScale",
      values: { default: 1, max: 2, min: 1 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Small scale, maximum density, and low threshold create a heavy glyph baseline before measuring render scale.",
        value: { density: 100, scale: 6, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "heavy ASCII animation frame budget stays smooth",
      browser: true,
      browserTestName: "browser perf: heavy ASCII animation frame budget",
      budget: {
        maxFrameGapMs: 120,
        maxLongTaskMs: 220,
      },
      expectedObservable:
        "The heaviest useful ASCII animation samples at least 120 frames without long frame gaps.",
      fixture: "scale 6, density 100, threshold 0.2, renderScale 2 animation",
      id: "heavy-animation-frame",
      interaction: "animation-frame",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-animation",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Small cells, maximum density, low threshold, and render scale 2 are the heaviest useful animated preview state.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
      target: "timeline.playback",
      values: {
        default: { density: 70, renderScale: 1, scale: 14, threshold: 0.6 },
        max: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
        min: { density: 12, renderScale: 1, scale: 28, threshold: 0.9 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "animated viewport drag coalesces heavy ASCII work",
      browser: true,
      browserTestName: "browser perf: animated viewport drag stays stable",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 2000,
        maxLongTaskMs: 220,
      },
      expectedObservable:
        "Dragging the canvas viewport during heavy animation keeps playback state and viewport stable.",
      fixture: "heavy ASCII animation viewport drag fixture",
      id: "animation-viewport-drag-heavy",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-animation",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "The same maximum animated preview state is used while the user drags the viewport.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
      target: "canvas.viewport",
      values: {
        default: { density: 70, renderScale: 1, scale: 14, threshold: 0.6 },
        max: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
        min: { density: 12, renderScale: 1, scale: 28, threshold: 0.9 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "viewport zoom stress avoids recomputing ASCII field",
      browser: true,
      browserTestName: "browser perf: viewport zoom stress uses heavy ASCII fixture",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 1500,
        maxLongTaskMs: 220,
      },
      expectedObservable:
        "Toolbar zoom under the heavy ASCII fixture does not resize or recompute the procedural field.",
      fixture: "heavy ASCII viewport zoom fixture",
      id: "viewport-zoom-stress-heavy",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-viewport",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "The heaviest preview state is applied before measuring toolbar zoom responsiveness.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
      target: "canvas.zoom",
      values: {
        default: { density: 70, renderScale: 1, scale: 14, threshold: 0.6 },
        max: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
        min: { density: 12, renderScale: 1, scale: 28, threshold: 0.9 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "short video export completes within budget",
      browser: true,
      browserTestName: "browser perf: short video export uses current export settings",
      budget: {
        maxExportMs: 8000,
      },
      expectedObservable:
        "A short current-size video export creates a non-empty blob within the export budget.",
      fixture: "1 second current-size ASCII video export fixture",
      id: "short-video-export",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 80, duration: 1, scale: 12, threshold: 0.35 },
          metric: "custom",
          smoothTarget: { density: 80, duration: 1, scale: 12, threshold: 0.35 },
          smoothTargetRatio: 1,
          target: "video-export-current",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "A one-second current-size export is the targeted browser performance checkpoint for export mechanics without making CI wait for the full reference duration.",
        value: { density: 80, duration: 1, scale: 12, threshold: 0.35 },
      },
      target: "actions.output",
      values: {
        default: { duration: 11.88166666666667, resolution: "current" },
        max: { duration: 11.88166666666667, resolution: "4k" },
        min: { duration: 1, resolution: "current" },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "particle type select changes glyph family within budget",
      browser: true,
      browserTestName: "browser perf: particle type select changes glyph family",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 900,
        maxLongTaskMs: 180,
      },
      controlLabel: "Particle",
      expectedObservable:
        "Changing the Particle select swaps the glyph family without stalling the ASCII preview.",
      fixture: "default ASCII preview with particle type changed to Hachures",
      id: "particle-type-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "hatch",
          metric: "custom",
          smoothTarget: "hatch",
          smoothTargetRatio: 1,
          target: "pattern.particleType",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Hachures exercises the diagonal glyph draw path across the full grid.",
        value: "hatch",
      },
      target: "pattern.particleType",
      values: { default: "cross", max: "hatch", min: "dot" },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Particle switching is measured inside the heaviest visible preview baseline.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "speed drag keeps timeline preview responsive",
      browser: true,
      browserTestName: "browser perf: speed control drag stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 900,
        maxLongTaskMs: 180,
      },
      controlLabel: "Speed",
      expectedObservable:
        "Dragging Speed changes timeline drift without changing glyph workload or causing preview jank.",
      fixture: "default animated ASCII preview with speed dragged",
      id: "speed-control-drag",
      interaction: "control-drag",
      target: "motion.speed",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "dither strength drag keeps preview responsive",
      browser: true,
      browserTestName: "browser perf: strength control drag stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 900,
        maxLongTaskMs: 180,
      },
      controlLabel: "Strength",
      expectedObservable:
        "Dragging Strength updates contrast math without resizing the ASCII grid.",
      fixture: "default ASCII preview with strength dragged",
      id: "strength-control-drag",
      interaction: "control-drag",
      target: "dither.strength",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "contrast drag keeps preview responsive",
      browser: true,
      browserTestName: "browser perf: contrast control drag stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 900,
        maxLongTaskMs: 180,
      },
      controlLabel: "Contrast",
      expectedObservable:
        "Dragging Contrast updates particle tone mapping without resizing the ASCII grid.",
      fixture: "default ASCII preview with contrast dragged",
      id: "contrast-control-drag",
      interaction: "control-drag",
      target: "dither.contrast",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "include background toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: include background toggle stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 700,
        maxLongTaskMs: 160,
      },
      controlLabel: "Include",
      expectedObservable:
        "Toggling Include changes background compositing without recomputing the ASCII field.",
      fixture: "default ASCII preview with background include toggled",
      id: "include-background-control-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: background color change stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 700,
        maxLongTaskMs: 160,
      },
      expectedObservable:
        "Changing Background updates the fill color without recomputing the ASCII field.",
      fixture: "default ASCII preview with background color edited",
      id: "background-color-control-change",
      interaction: "control-change",
      target: "appearance.background",
      uiSelector: "[aria-label='background hex']",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image format select stays responsive",
      browser: true,
      browserTestName: "browser perf: image format select stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 700,
        maxLongTaskMs: 160,
      },
      controlLabel: "Format",
      expectedObservable:
        "Changing image Format updates export settings without changing preview workload.",
      fixture: "Image Export format changed to JPG",
      id: "image-format-control-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image resolution select records heavy export range",
      browser: true,
      browserTestName: "browser perf: image resolution select records heavy export range",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 700,
        maxLongTaskMs: 160,
      },
      controlLabel: "Resolution",
      expectedObservable:
        "Changing Image Export Resolution records the 2K to 8K export workload range without preview jank.",
      fixture: "Image Export resolution changed across 2K, 4K, and 8K",
      id: "image-resolution-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the maximum still image export size exposed by the control.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Export resolution changes are measured after applying the heaviest preview baseline.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "video format select stays responsive",
      browser: true,
      browserTestName: "browser perf: video format select stays responsive",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 700,
        maxLongTaskMs: 160,
      },
      controlLabel: "Format",
      expectedObservable:
        "Changing video Format updates recorder settings without changing preview workload.",
      fixture: "Video Export format changed to WebM",
      id: "video-format-control-change",
      interaction: "control-change",
      target: "export.video.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "video resolution select records encoder workload range",
      browser: true,
      browserTestName: "browser perf: video resolution select records encoder workload range",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 700,
        maxLongTaskMs: 160,
      },
      controlLabel: "Resolution",
      expectedObservable:
        "Changing Video Export Resolution records the current to 4K encoder workload range without preview jank.",
      fixture: "Video Export resolution changed from Current to 4K",
      id: "video-resolution-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: "4k",
          metric: "custom",
          smoothTarget: "4k",
          smoothTargetRatio: 1,
          target: "export.video.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K is the maximum video encoder resolution exposed by the control.",
        value: "4k",
      },
      target: "export.video.resolution",
      values: { default: "current", max: "4k", min: "current" },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Video resolution changes are measured after applying the heaviest preview baseline.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
    },
    {
      automated: true,
      automatedTestName: "heavy preview render completes within budget",
      browser: true,
      browserTestName: "browser perf: heavy preview render completes within budget",
      budget: {
        maxLongTaskMs: 220,
        maxPreviewMs: 900,
      },
      expectedObservable:
        "Applying the heaviest preview fixture renders a visible ASCII frame within budget.",
      fixture: "scale 6, density 100, threshold 0.2, renderScale 2 preview",
      id: "heavy-preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          metric: "custom",
          smoothTarget: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
          smoothTargetRatio: 1,
          target: "combined-heavy-preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Small cells, maximum density, low threshold, and render scale 2 are the heaviest visible preview state.",
        value: { density: 100, renderScale: 2, scale: 6, threshold: 0.2 },
      },
      target: "canvas.preview",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "viewport stays stable after product controls",
      browser: true,
      browserTestName: "browser perf: viewport stability after controls",
      budget: {
        maxFrameGapMs: 120,
        maxInteractionMs: 900,
        maxLongTaskMs: 180,
      },
      expectedObservable:
        "Changing product controls does not shift the Toolcraft canvas viewport.",
      fixture: "default ASCII preview with Density dragged during viewport stability check",
      id: "viewport-stability-after-controls",
      interaction: "viewport-stability",
      target: "canvas.viewport",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "pattern.particleType",
    "pattern.scale",
    "pattern.spacing",
    "pattern.voids",
    "pattern.density",
    "dither.threshold",
    "export.image.resolution",
    "export.video.resolution",
    "canvas.renderScale",
  ],
});
